import Link from "next/link";
import { ArrowLeft, Check } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";

export function PageHero({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) {
  return <section className="relative overflow-hidden border-b border-[var(--hairline)] bg-[var(--surface-sunken)] py-16 sm:py-24"><div className="grid-backdrop absolute inset-0 pointer-events-none"/><div className="container-page relative"><nav aria-label="مسیر صفحه" className="mb-10 flex gap-3 text-xs text-muted"><Link href="/" className="hover:text-brand-600">کارن سافت</Link><span>/</span><span>{title}</span></nav><span className="eyebrow">{eyebrow}</span><h1 className="display-1 mt-5 max-w-4xl">{title}</h1><p className="lead mt-6">{description}</p>{children && <div className="mt-8 flex flex-wrap gap-3">{children}</div>}</div></section>;
}
export function ContentSection({ title, children, id }: { title: string; children: React.ReactNode; id?: string }) { return <section id={id} className="container-page py-12 sm:py-16"><h2 className="display-3 mb-8">{title}</h2>{children}</section>; }
export function Points({ items }: { items: readonly string[] }) { return <ul className="space-y-4">{items.map(x=><li key={x} className="flex gap-3 leading-loose"><Check className="mt-1 size-5 shrink-0 text-brand-500"/><span>{x}</span></li>)}</ul>; }
export function InfoGrid({ items }: { items: readonly { title: string; desc: string }[] }) { return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{items.map((x,i)=><article key={x.title} className="surface-card p-7"><span className="sec-index">{String(i+1).padStart(2,"0")}</span><h3 className="mt-4 mb-3">{x.title}</h3><p className="text-muted leading-loose">{x.desc}</p></article>)}</div>; }
export function ContactCTA() { return <section className="container-page py-16"><div className="rounded-[var(--radius-2xl)] bg-ink-900 p-8 sm:p-14 text-white flex flex-wrap items-center justify-between gap-8"><div><span className="eyebrow !text-brand-300">LET’S BUILD TOGETHER</span><h2 className="display-3 mt-4">قدم بعدی، یک گفت‌وگوی ساده است.</h2><p className="mt-3 text-white/60">نیازتان را بگویید؛ مسیر اجرا را با هم مشخص می‌کنیم.</p></div><ButtonLink href="/contact">شروع گفت‌وگو <ArrowLeft className="size-4"/></ButtonLink></div></section>; }
