import { JsonLd } from "@/components/ui/json-ld";
import { articleSchema } from "@/lib/schema";
import { ArticleBlocks } from "@/components/site/article-blocks";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BLOG_POSTS } from "@/lib/blog";
import { pageMeta } from "@/lib/seo";
import { PageHero, ContentSection, ContactCTA } from "@/components/site/page-parts";
export const generateStaticParams=()=>BLOG_POSTS.map(p=>({slug:p.slug}));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=BLOG_POSTS.find(p=>p.slug===slug);return p?pageMeta({title:p.title,description:p.excerpt,path:`/blog/${slug}`,images:[p.cover]}):{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=BLOG_POSTS.find(p=>p.slug===slug);if(!p)notFound();return <><PageHero eyebrow="KAREN JOURNAL" title={p.title} description={p.excerpt}><p className="text-xs text-muted">{p.author} · {new Date(p.date).toLocaleDateString("fa-IR")} · {p.readingMinutes.toLocaleString("fa-IR")} دقیقه مطالعه</p></PageHero><div className="container-page py-12 grid gap-12 lg:grid-cols-[240px_1fr]"><aside><nav aria-label="فهرست مقاله" className="surface-card p-6 lg:sticky lg:top-28"><h2 className="text-lg mb-5">در این مقاله</h2>{p.sections.map((s,i)=><a key={s.heading} className="block border-b py-3 text-sm text-muted hover:text-brand-600" href={`#section-${i}`}>{s.heading}</a>)}<Link className="inline-block mt-6 text-brand-600 dark:text-brand-300" href="/blog">همه مقاله‌ها ←</Link></nav></aside><article className="min-w-0 max-w-3xl">{p.sections.some(s=>s.blocks) && <aside className="surface-card p-5 mb-8 text-xs text-muted">این مطلب از آرشیو کارن سافت منتقل شده است. اشاره به قیمت، رایگان بودن یا قابلیت‌ها مربوط به نسخه زمان نگارش است؛ برای شرایط فعلی، صفحه محصول را بررسی کنید. <a className="text-brand-600 dark:text-brand-300 underline" href={`https://github.com/rahmaniho/karen-soft/blob/main/legacy${p.legacyPath}`}>نسخه اصلی در مخزن</a></aside>}<div className="relative aspect-video overflow-hidden rounded-2xl mb-10"><Image src={p.cover} alt={p.title} fill sizes="(max-width: 767px) 100vw, 900px" className="object-cover" priority/></div>{p.sections.map((s,i)=><section key={s.heading} id={`section-${i}`} className="mb-12"><h2 className="text-2xl mb-5">{s.heading}</h2>{s.blocks && <ArticleBlocks blocks={s.blocks}/>} {s.paragraphs.map(t=><p key={t} className="text-base leading-loose text-muted mb-4">{t}</p>)}{s.bullets&&<ul className="list-disc ps-6 space-y-3 text-muted leading-loose">{s.bullets.map(t=><li key={t}>{t}</li>)}</ul>}</section>)}<div className="flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full border px-4 py-2 text-xs">{t}</span>)}</div></article></div><ContentSection title="برای مطالعه بیشتر"><div className="grid gap-5 md:grid-cols-3">{BLOG_POSTS.filter(x=>x.slug!==slug).slice(0,3).map(x=><Link className="surface-card p-6" key={x.slug} href={`/blog/${x.slug}`}><p className="text-xs text-brand-600 dark:text-brand-300">{x.category}</p><h3 className="mt-3">{x.title}</h3></Link>)}</div></ContentSection><ContactCTA/><JsonLd data={articleSchema(p)}/></>}
