import { notFound } from "next/navigation";
import { PRODUCTS, PRODUCT_STATUS_LABEL } from "@/lib/products";
import { pageMeta } from "@/lib/seo";
import { PageHero, ContentSection, InfoGrid, Points, ContactCTA } from "@/components/site/page-parts";
import { ButtonLink } from "@/components/ui/button";
import { Accordion } from "@/components/ui/accordion";
import { FAQS } from "@/lib/constants";
export const generateStaticParams=()=>PRODUCTS.map(p=>({slug:p.slug}));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const p=PRODUCTS.find(p=>p.slug===slug); return p?pageMeta({title:p.name,description:p.short,path:`/products/${slug}`}):{}; }
export default async function Page({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const p=PRODUCTS.find(p=>p.slug===slug); if(!p) notFound(); return <><PageHero eyebrow="PRODUCT / KAREN SOFT" title={p.name} description={p.description}><ButtonLink href={`/demo/${p.demoSlug}`}>تجربه دموی زنده</ButtonLink><ButtonLink href="/contact" variant="outline">درخواست مشاوره</ButtonLink></PageHero><ContentSection title="در یک نگاه"><div className="surface-card p-8 grid gap-8 md:grid-cols-3"><div><p className="text-muted">وضعیت محصول</p><h3>{PRODUCT_STATUS_LABEL[p.status]}</h3></div><div><p className="text-muted">شروع قیمت پایه</p><h3>{p.pricingFrom.toLocaleString("fa-IR")} تومان</h3><p className="text-xs text-muted mt-2">قیمت نهایی پس از بررسی دامنه و تأیید پیشنهاد تعیین می‌شود.</p></div><div><p className="text-muted">امکان بررسی پیش از خرید</p><h3>دموی مرورگری با داده نمونه</h3></div></div></ContentSection>{p.slug === "law-office" && <ContentSection title="دریافت نسخه نرم‌افزار"><ButtonLink href="/download-law-software" variant="outline">راهنمای دریافت و نصب</ButtonLink></ContentSection>}<ContentSection title="قابلیت‌های کلیدی"><Points items={p.features}/></ContentSection><ContentSection title="همه ماژول‌ها، یک تجربه یکپارچه"><InfoGrid items={p.modules}/></ContentSection>{p.solution&&<ContentSection title="راهکار تخصصی صنعت شما"><ButtonLink href={`/solutions/${p.solution}`} variant="soft">بررسی فرایندها و راهکار صنعت</ButtonLink></ContentSection>}<ContentSection title="پیش از شروع بدانید"><Accordion items={FAQS}/></ContentSection><ContactCTA/></>; }
