import Image from "next/image";
import { notFound } from "next/navigation";
import { CASE_STUDIES } from "@/lib/portfolio";
import { pageMeta } from "@/lib/seo";
import { PageHero, ContentSection, Points, ContactCTA } from "@/components/site/page-parts";
import { ButtonLink } from "@/components/ui/button";
export const generateStaticParams=()=>CASE_STUDIES.map(p=>({slug:p.slug}));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=CASE_STUDIES.find(p=>p.slug===slug);return p?pageMeta({title:p.title,description:p.summary,path:`/portfolio/${slug}`}):{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=CASE_STUDIES.find(p=>p.slug===slug);if(!p)notFound();return <><PageHero eyebrow="CASE STUDY" title={p.title} description={p.summary}><p>{p.client} · {p.category} · {p.year}</p></PageHero><div className="container-page py-12"><div className="relative aspect-[16/9] rounded-2xl overflow-hidden bg-[var(--surface-sunken)]"><Image src={p.cover} alt={p.title} fill sizes="(max-width: 767px) 100vw, 900px" className="object-contain" priority/></div></div><ContentSection title="چالش پروژه"><Points items={p.challenge}/></ContentSection><ContentSection title="راه‌حل و اجرا"><Points items={p.solution}/></ContentSection><ContentSection title="نتایج ثبت‌شده پروژه"><div className="grid gap-5 sm:grid-cols-3">{p.results.map(x=><div className="surface-card p-8" key={x.label}><p className="text-4xl text-brand-600 dark:text-brand-300">{x.value}</p><p className="mt-3 text-muted">{x.label}</p></div>)}</div></ContentSection><ContentSection title="خدمات و فناوری‌ها"><Points items={p.services}/><div className="mt-8 flex flex-wrap gap-3">{p.stack.map(x=><span key={x} className="rounded-full border px-4 py-2">{x}</span>)}</div></ContentSection>{p.quote&&<ContentSection title="از زبان مشتری"><blockquote className="surface-card p-8 text-xl">«{p.quote.text}»<footer className="text-sm mt-5 text-muted">{p.quote.author}</footer></blockquote></ContentSection>}{p.industryDemo&&<ContentSection title="یک تجربه مشابه را امتحان کنید"><ButtonLink href={`/demo/industries/${p.industryDemo}`}>مشاهده دموی صنعت</ButtonLink></ContentSection>}<ContactCTA/></>}
